version: '2'

services:
  mysql:
    image: bitnami/mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=odnel
    volumes:
      - ./database/mysql-persistence:/bitnami/mysql/data
    ports:
      - "3306:3306"